src/Form/MediaType.php
<?php

namespace TonySchmitt\MediaBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Vich\UploaderBundle\Form\Type\VichImageType;
// ... use FormType... (text, choice...)

class MediaType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options) {

    if(isset($_GET['provider'])) {
      switch ($_GET['provider']) {
        case 'youtube':
          $builder
          ->add('name', TextType::class, array('label' => 'Lien Youtube :'))
          ;
          break;
        case 'vimeo':
          $builder
          ->add('name', TextType::class, array('label' => 'Lien Vimeo :'))
          ;
          break;
        case 'file':
          $builder
          ->add('name', TextType::class, array('label' => 'Nom du fichier :'))
          ->add('mediaFile', VichImageType::class, array('label' => 'Fichier :'))
          ;
          break;
        case 'bigFile':
          $builder
          ->add('name', TextType::class, array('label' => 'Nom du fichier :'))
          ->add('mediaFile', VichImageType::class, array('label' => 'Fichier :'))
          ->add('originalFilename', TextType::class, array('label' => 'Nom du fichier :'))
          ;
          break;
        case 'pdf':
          $builder
          ->add('name', TextType::class, array('label' => 'Nom du fichier PDF :'))
          ->add('mediaFile', VichImageType::class, array('label' => 'Fichier PDF :'))
          ;
          break;


        default:
          $builder
          ->add('name', TextType::class, array('label' => 'Nom de l\'image :'))
          ->add('mediaFile', VichImageType::class, array('label' => 'Image :'))
          ;
          break;
      }

    } else {
      $builder
      ->add('name', TextType::class, array('label' => 'Nom de l\'image :'))
      ->add('mediaFile', VichImageType::class, array('label' => 'Image :'))
      ;
    }
  }
}

src/Form/Module/GalleryModuleType.php
<?php

namespace TonySchmitt\MediaBundle\Form\Module;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use TonySchmitt\MediaBundle\Entity\Module\GalleryModule;
// ... use FormType... (text, choice...)

class GalleryModuleType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options) {

    $builder
    ->add('id', HiddenType::class, array('required' => false))
    ->add('gallery')
    ;
  }

  /**
   * @param OptionsResolver $resolver
   */
  public function configureOptions(OptionsResolver $resolver)
  {
      $resolver->setDefaults(array(
          'data_class' => 'TonySchmitt\MediaBundle\Entity\Module\GalleryModule'
      ));
  }
}

src/Form/Module/ListGalleryModuleType.php
<?php

namespace TonySchmitt\MediaBundle\Form\Module;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use TonySchmitt\MediaBundle\Entity\Module\ListGalleryModule;
// ... use FormType... (text, choice...)

class ListGalleryModuleType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options) {

    $builder
    ->add('id', HiddenType::class, array('required' => false))
    ->add('galleries')
    ;
  }

  /**
   * @param OptionsResolver $resolver
   */
  public function configureOptions(OptionsResolver $resolver)
  {
      $resolver->setDefaults(array(
          'data_class' => 'TonySchmitt\MediaBundle\Entity\Module\ListGalleryModule'
      ));
  }
}

src/Form/Type/MediaListChoiceType.php
<?php

namespace TonySchmitt\MediaBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class MediaListChoiceType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'multiple' => true,
            'data_class' => null,
            'allow_add' => true,
            'allow_remove' => true,
        ));
    }

    public function getParent()
    {
        return CollectionType::class;
    }

    public function getBlockPrefix()
    {
        return 'tonyschmitt_media_list_choice';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/Resources/views/form/fields.html.twig
{% block tonyschmitt_media_list_choice_widget %}
    <div class="row grid" id="gallery_media_preview">
        {% set input = "" %}
        {% for mediaElement in form.parent.vars.value.medias %}
            {% set media = mediaElement.media %}
            <div id="media{{media.id}}" class="col-sm-3">
                <div style="position: relative; height: 200px; overflow: hidden; border-radius: 5px; border: 1px solid #b1b1b1; {% if media.provider != 'file' and media.provider != 'pdf' %}background: url('{{ media.directory ~ 'thumb_default_' ~ media.id ~ '_small.' ~ media.extension }}'); background-size: cover;{% elseif media.provider == 'pdf' %}background: url(/bundles/tonyschmittmedia/images/pdf.png); background-size: 80%; background-position: center; background-repeat: no-repeat;{% endif %}">
                    <div class="" style="position: absolute; bottom: 0px; background-color: white; width: 100%; color: #0091ff; padding: 4px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                        {{ media.name }}
                    </div>
                    <div class="" style="position: absolute; top: 10px; right: 10px; background-color: #00b8ff; color: white; padding: 3px; border-radius: 7px;">
                        {{ media.provider }}
                    </div>
                    <div class="tonyschmitt_gallery_media_id" media_id="{{ media.id }}" style="position: absolute; top: 10px; left: 10px; color: red; cursor: pointer;">
                        X
                    </div>
                    <div style="position: absolute; top: 75px; left: 10px; color: black; cursor: pointer;">
                        <i class="fa fa-arrow-left" aria-hidden="true" onclick="moveMediaToLeft(this)"></i>
                    </div>
                    <div style="position: absolute; top: 75px; right: 10px; color: black; cursor: pointer;">
                        <i class="fa fa-arrow-right" aria-hidden="true" onclick="moveMediaToRight(this)"></i>
                    </div>
                </div>
                <input class="tonyschmitt_gallery_media" type="hidden" name="gallery[medias][]" value="{{ media.id }}" />
            </div>
        {% endfor %}
    </div>
    <br>
    <div onclick="mediaAJAX()" style="color: #0091ff; cursor: pointer;">+ Ajouter un media</div>
    <div onclick="uploadMedias()" style="color: #0091ff; cursor: pointer;">+ Uploader plusieurs medias (En utilisant cette option vous perdrez tout autre changement).</div>
    <div id="container" style="position: fixed; z-index: 1040; top: 10%; left: 15%; width: 70%; height: 80%; background-color: white; border-radius: 10px; border: 1px solid black; overflow: hidden;"></div>
    <div id="containerUpload" style="position: fixed; z-index: 1040; top: 10%; left: 15%; width: 70%; height: 80%; background-color: white; border-radius: 10px; border: 1px solid black; overflow: hidden;">
        <div id="uploader"></div>
        <script type="text/template" id="qq-template">
            <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
                <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
                </div>
                <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone="qq-hide-dropzone">
                    <span class="qq-upload-drop-area-text-selector"></span>
                </div>
                <div class="qq-upload-button-selector qq-upload-button">
                    <div>Select files</div>
                </div>
                <span class="qq-drop-processing-selector qq-drop-processing">
                    <span>Processing dropped files...</span>
                    <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
                </span>
                <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
                    <li>
                        <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                        <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                        </div>
                        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                        <div class="qq-thumbnail-wrapper">
                            <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale="qq-server-scale">
                        </div>
                        <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                        <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                            <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                            Retry
                        </button>

                        <div class="qq-file-info">
                            <div class="qq-file-name">
                                <span class="qq-upload-file-selector qq-upload-file"></span>
                                <span class="qq-edit-filename-icon-selector qq-btn qq-edit-filename-icon" aria-label="Edit filename"></span>
                            </div>
                            <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                            <span class="qq-upload-size-selector qq-upload-size"></span>
                            <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                                <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                            </button>
                            <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                                <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                            </button>
                            <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                                <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                            </button>
                        </div>
                    </li>
                </ul>

                <dialog class="qq-alert-dialog-selector">
                    <div class="qq-dialog-message-selector"></div>
                    <div class="qq-dialog-buttons">
                        <button type="button" class="qq-cancel-button-selector">Close</button>
                    </div>
                </dialog>

                <dialog class="qq-confirm-dialog-selector">
                    <div class="qq-dialog-message-selector"></div>
                    <div class="qq-dialog-buttons">
                        <button type="button" class="qq-cancel-button-selector">No</button>
                        <button type="button" class="qq-ok-button-selector">Yes</button>
                    </div>
                </dialog>

                <dialog class="qq-prompt-dialog-selector">
                    <div class="qq-dialog-message-selector"></div>
                    <input type="text">
                    <div class="qq-dialog-buttons">
                        <button type="button" class="qq-cancel-button-selector">Cancel</button>
                        <button type="button" class="qq-ok-button-selector">Ok</button>
                    </div>
                </dialog>
            </div>
        </script>
        <script src="/bundles/tonyschmittmedia/fine-uploader/fine-uploader.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                var uploader = new qq.FineUploader({
                    element: document.getElementById('uploader'),
                    request: {
                        endpoint: "{{ oneup_uploader_endpoint('gallery') }}"
                    },
                    chunking: {
                        enabled: true,
                        partSize: 100000
                    },
                    multiple: true,
                    callbacks: {
                        onComplete: function (event, id, fileName, responseJSON) {
                          listMediasUploads.push([JSON.parse(responseJSON.response).filename, id]);
                            $('#media_mediaFile_file').val(JSON.parse(responseJSON.response).filename);
                            $('#media_originalFilename').val(id);
                        }
                    }
                });
            });
        </script>

        <div id="fine-uploader"></div>
        <button class="btn btn-success" onclick="UploadFiles();return false;">Upload</button>
        <p>ATTENTION : Après avoir appuyé sur ce bouton, le navigateur va recharger la page au bout de quelques secondes. Merci de l'autoriser à recharger la page malgré la pop-up qui demande une confirmation suite aux modifications de la page.</p>
    </div>
    <script type="text/javascript">
        var listMediasUploads = new Array();
        $(document).ready(function () {
            $(".field-collection-action").remove();
        });

        $(document).on("click", ".tonyschmitt_gallery_media_id", function (e) {
            var id = $(this).attr("media_id");
            $(this).parent().parent().remove();
            $(".tonyschmitt_gallery_media[value='" + id + "']").remove();
        });

        $("#container").hide();
        $("#containerUpload").hide();

        $(document).on("click", "#close_gallery", function (e) {
            $("#container").hide();
            $("#containerUpload").hide();
        });

        function UploadFiles() {
          $.post( "/admin/ajax/upload/files", { id: {{ form.parent.vars.value.id }}, files: listMediasUploads } )
          .done(function( data ) {
            location.reload(true);
          });
          event.preventDefault();
        }

        function uploadMedias() {
          $("#containerUpload").append('<div id="close_gallery" style="cursor: pointer; position: absolute; top: 10px; right: 20px; font-size: 20px; color: red; font-weight"><i class="fa fa-window-close" aria-hidden="true"></i></div>');
          $("#containerUpload").show();
        }

        function mediaAJAX() {
            $("#container").load("/admin/?action=list&entity=Media #main", function () {
                $("#container").append('<div id="close_gallery" style="cursor: pointer; position: absolute; top: 10px; right: 20px; font-size: 20px; color: red; font-weight"><i class="fa fa-window-close" aria-hidden="true"></i></div>');
                $("#container").show();
            });
        }

        function moveMediaToLeft(element) {
          $(element).parent().parent().parent().insertBefore($(element).parent().parent().parent().prev());
        }

        function moveMediaToRight(element) {
          $(element).parent().parent().parent().insertAfter($(element).parent().parent().parent().next());
        }

        $(document).on("click", "#container a", function (e) {
            var url = this.href;
            url_get = url.split("?")[1];
            var param = [];
            url_get.split("&").forEach(function (element) {
                element_split = element.split("=");
                param[element_split[0]] = element_split[1];
            });
            if (param["action"] && param["action"] == "list") {
                $("#container").load(url + " #main", function () {
                    $("#container").append('<div id="close_gallery" style="cursor: pointer; position: absolute; top: 10px; right: 20px; font-size: 20px; color: red; font-weight"><i class="fa fa-window-close" aria-hidden="true"></i></div>');
                });
            }
            if (param["action"] && param["action"] == "edit") {
                var content = $(this);
                content.children(content.children().append('<div class="tonyschmitt_gallery_media_id" media_id="' + param["id"] + '" style="position: absolute; top: 10px; left: 10px; color: red; cursor: pointer;">X</div>'));
                $("#gallery_media_preview").append('<div class="col-sm-3">' + content.html() + '<input class="tonyschmitt_gallery_media" type="hidden" name="gallery[medias][]" value="' + param["id"] + '" />' + "</div>");
                $("#container").hide();
                $("#containerUpload").hide();
            }
            e.preventDefault();
        });
    </script>
{% endblock %}